{
  "affected": [
    {
      "database_specific": {
        "source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2021-28210.json"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "06dc822d045c2bb42e497487935485302486e151"
            }
          ],
          "repo": "https://github.com/tianocore/edk2",
          "type": "GIT"
        }
      ],
      "versions": [
        "edk2-stable201808",
        "edk2-stable201811",
        "edk2-stable201903",
        "edk2-stable201905",
        "edk2-stable201908",
        "edk2-stable201911",
        "edk2-stable202002",
        "edk2-stable202005"
      ]
    }
  ],
  "details": "An unlimited recursion in DxeCore in EDK II.",
  "id": "CVE-2021-28210",
  "modified": "2025-09-24T10:43:42.785631Z",
  "published": "2021-06-11T16:15:12Z",
  "references": [
    {
      "type": "REPORT",
      "url": "https://bugzilla.tianocore.org/show_bug.cgi?id=1743"
    }
  ],
  "related": [
    "SUSE-SU-2021:0972-1",
    "SUSE-SU-2021:0987-1",
    "SUSE-SU-2021:2117-1",
    "SUSE-SU-2021:2161-1",
    "openSUSE-SU-2021:0495-1",
    "openSUSE-SU-2024:11134-1"
  ],
  "schema_version": "1.7.3",
  "severity": [
    {
      "score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
      "type": "CVSS_V3"
    }
  ]
}