{
  "affected": [
    {
      "database_specific": {
        "source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2021-29530.json",
        "vanir_signatures": [
          {
            "deprecated": false,
            "digest": {
              "line_hashes": [
                "253781478397541056602689406463014838958",
                "239560922857308828919157851601272280929",
                "280711993339257124038781815470371329037",
                "205090741053361526681941472168103285574",
                "121946168169142239614567311044557000014",
                "89783717097941851157565793427942842478",
                "28972579787471686773729522611243035204",
                "311823163073068944011776732932071184318",
                "296878916593624319768100602367596172954",
                "255967630873613548701264099863185083856",
                "260870806742725755014545069736338714846",
                "214985371609828385320743754504512928578",
                "194470700351065301689674946308411906892",
                "21325521787577701379505581389811486509",
                "175750355588109615123289094420149349357",
                "96936261567771253156925096846107220815",
                "14014010318667349279570987137102121057",
                "45959256262558526328153025040865236802",
                "304199593083152093320124538432500244808",
                "274706543680024705398874828629765198453",
                "80470081812361228662722619050302491090",
                "15630166823741107531637766925156438067",
                "168307337367787846154540922106810935219",
                "275135145937553463084677149015795725311",
                "127671899323606939144055113861206734623",
                "306861041691438897677301544136695638205",
                "307669638991137709776520653745912930877",
                "5687570855211274080550150991624986348",
                "127050220195203212942599071205006030273",
                "288457066491466488746535658527327104655",
                "146129390556571693719022638557521853446",
                "183363277977567025938066774229162175409",
                "43581517195697618132229909117580499422",
                "171365111257850579948939170529609886377",
                "140809007161098837781433933020177554659",
                "142588258317183017402260634446745893566",
                "130106211139833448463966603537732320358",
                "326977632074968974300616639522420919582",
                "262314191185911328371145091567193517656",
                "261598356254991826953734235852749118995",
                "44124725594456650662205956441308050567",
                "14478431743598174032197323092021278185",
                "9108933313667840532796487540082086815",
                "284058706955699957258638976439423242433",
                "88760001953405681975565764395957190954",
                "12431736038571622175522060094770234020",
                "287127589613663426338055858168067774780",
                "325966101634517283622955065444791650130",
                "14309112608701686400098650250032605995",
                "283225996118914251767355321496948224279",
                "288080263079928045858847493184662451430",
                "234247219865892728865002434907009707769"
              ],
              "threshold": 0.9
            },
            "id": "CVE-2021-29530-bd98f96b",
            "signature_type": "Line",
            "signature_version": "v1",
            "source": "https://github.com/tensorflow/tensorflow/commit/e6a7c7cc18c3aaad1ae0872cb0a959f5c923d2bd",
            "target": {
              "file": "tensorflow/core/kernels/sparse/sparse_cholesky_op.cc"
            }
          }
        ]
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "e6a7c7cc18c3aaad1ae0872cb0a959f5c923d2bd"
            }
          ],
          "repo": "https://github.com/tensorflow/tensorflow",
          "type": "GIT"
        }
      ],
      "versions": [
        "0.12.0-rc0",
        "0.12.0-rc1",
        "0.12.1",
        "0.5.0",
        "0.6.0",
        "v0.10.0",
        "v0.10.0rc0",
        "v0.11.0",
        "v0.11.0rc0",
        "v0.11.0rc1",
        "v0.11.0rc2",
        "v0.12.0",
        "v0.7.0",
        "v0.7.1",
        "v0.8.0rc0",
        "v0.9.0",
        "v0.9.0rc0",
        "v1.0.0",
        "v1.0.0-alpha",
        "v1.0.0-rc0",
        "v1.0.0-rc1",
        "v1.0.0-rc2",
        "v1.1.0",
        "v1.1.0-rc0",
        "v1.1.0-rc1",
        "v1.1.0-rc2",
        "v1.12.0",
        "v1.12.0-rc0",
        "v1.12.0-rc1",
        "v1.12.0-rc2",
        "v1.12.1",
        "v1.2.0",
        "v1.2.0-rc0",
        "v1.2.0-rc1",
        "v1.2.0-rc2",
        "v1.3.0-rc0",
        "v1.3.0-rc1",
        "v1.5.0",
        "v1.5.0-rc0",
        "v1.5.0-rc1",
        "v1.6.0",
        "v1.6.0-rc0",
        "v1.6.0-rc1",
        "v1.7.0",
        "v1.7.0-rc0",
        "v1.7.0-rc1",
        "v1.8.0",
        "v1.8.0-rc0",
        "v1.8.0-rc1",
        "v1.9.0",
        "v1.9.0-rc0",
        "v1.9.0-rc1",
        "v1.9.0-rc2"
      ]
    }
  ],
  "aliases": [
    "BIT-tensorflow-2021-29530",
    "GHSA-xcwj-wfcm-m23c",
    "PYSEC-2021-167",
    "PYSEC-2021-458",
    "PYSEC-2021-656"
  ],
  "details": "TensorFlow is an end-to-end open source platform for machine learning. An attacker can trigger a null pointer dereference by providing an invalid `permutation` to `tf.raw_ops.SparseMatrixSparseCholesky`. This is because the implementation(https://github.com/tensorflow/tensorflow/blob/080f1d9e257589f78b3ffb75debf584168aa6062/tensorflow/core/kernels/sparse/sparse_cholesky_op.cc#L85-L86) fails to properly validate the input arguments. Although `ValidateInputs` is called and there are checks in the body of this function, the code proceeds to the next line in `ValidateInputs` since `OP_REQUIRES`(https://github.com/tensorflow/tensorflow/blob/080f1d9e257589f78b3ffb75debf584168aa6062/tensorflow/core/framework/op_requires.h#L41-L48) is a macro that only exits the current function. Thus, the first validation condition that fails in `ValidateInputs` will cause an early return from that function. However, the caller will continue execution from the next line. The fix is to either explicitly check `context->status()` or to convert `ValidateInputs` to return a `Status`. The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range.",
  "id": "CVE-2021-29530",
  "modified": "2025-10-14T18:28:04.509310Z",
  "published": "2021-05-14T20:15:11Z",
  "references": [
    {
      "type": "FIX",
      "url": "https://github.com/tensorflow/tensorflow/commit/e6a7c7cc18c3aaad1ae0872cb0a959f5c923d2bd"
    },
    {
      "type": "FIX",
      "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-xcwj-wfcm-m23c"
    }
  ],
  "related": [
    "GHSA-xcwj-wfcm-m23c"
  ],
  "schema_version": "1.7.3",
  "severity": [
    {
      "score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
      "type": "CVSS_V3"
    }
  ]
}