{
  "affected": [
    {
      "database_specific": {
        "source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2020-14330.json"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "40091190b267a697e4061ba0d351236e91f5c0d2"
            }
          ],
          "repo": "https://github.com/ansible/ansible",
          "type": "GIT"
        }
      ],
      "versions": [
        "0.0.1",
        "0.0.2",
        "0.01",
        "0.3",
        "0.7",
        "stable-2.9-branchpoint",
        "v1.0",
        "v1.1",
        "v1.2",
        "v1.4.0",
        "v1.5.0",
        "v1.5.1",
        "v1.6.0",
        "v1_last",
        "v2.0.0-0.1.alpha1",
        "v2.0.0-0.2.alpha2",
        "v2.0.0-0.3.beta1",
        "v2.0.0-0.4.beta2",
        "v2.0.0-0.5.beta3",
        "v2.6.0a1",
        "v2.7.0.a1",
        "v2.8.0a1",
        "v2.9.0",
        "v2.9.0b1",
        "v2.9.0rc1",
        "v2.9.0rc2",
        "v2.9.0rc3",
        "v2.9.0rc4",
        "v2.9.0rc5",
        "v2.9.1",
        "v2.9.10",
        "v2.9.11",
        "v2.9.2",
        "v2.9.3",
        "v2.9.4",
        "v2.9.5",
        "v2.9.6",
        "v2.9.7",
        "v2.9.8",
        "v2.9.9"
      ]
    }
  ],
  "aliases": [
    "GHSA-785x-qw4v-6872",
    "PYSEC-2020-3"
  ],
  "details": "An Improper Output Neutralization for Logs flaw was found in Ansible when using the uri module, where sensitive data is exposed to content and json output. This flaw allows an attacker to access the logs or outputs of performed tasks to read keys used in playbooks from other users within the uri module. The highest threat from this vulnerability is to data confidentiality.",
  "id": "CVE-2020-14330",
  "modified": "2025-10-10T02:27:10.701181Z",
  "published": "2020-09-11T18:15:13Z",
  "references": [
    {
      "type": "REPORT",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-14330"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/ansible/ansible/issues/68400"
    },
    {
      "type": "ADVISORY",
      "url": "https://www.debian.org/security/2021/dsa-4950"
    }
  ],
  "related": [
    "SUSE-SU-2020:3309-1",
    "SUSE-SU-2024:1509-1",
    "openSUSE-SU-2022:0081-1",
    "openSUSE-SU-2024:10615-1",
    "openSUSE-SU-2024:14244-1",
    "openSUSE-SU-2024:14536-1"
  ],
  "schema_version": "1.7.3",
  "severity": [
    {
      "score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
      "type": "CVSS_V3"
    }
  ]
}