{
  "affected": [
    {
      "database_specific": {
        "source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2022-29228.json"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "ae27fb5280d30e1400b7e9c9cbd448bfcd4ad9f5"
            }
          ],
          "repo": "https://github.com/envoyproxy/envoy",
          "type": "GIT"
        }
      ],
      "versions": []
    }
  ],
  "aliases": [
    "BIT-envoy-2022-29228",
    "GHSA-rww6-8h7g-8jf6"
  ],
  "details": "Envoy is a cloud-native high-performance proxy. In versions prior to 1.22.1 the OAuth filter would try to invoke the remaining filters in the chain after emitting a local response, which triggers an ASSERT() in newer versions and corrupts memory on earlier versions. continueDecoding() shouldn\u2019t ever be called from filters after a local reply has been sent. Users are advised to upgrade. There are no known workarounds for this issue.",
  "id": "CVE-2022-29228",
  "modified": "2025-10-14T19:13:17.978634Z",
  "published": "2022-06-09T19:20:13Z",
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/envoyproxy/envoy/security/advisories/GHSA-rww6-8h7g-8jf6"
    },
    {
      "type": "FIX",
      "url": "https://github.com/envoyproxy/envoy/commit/7ffda4e809dec74449ebc330cebb9d2f4ab61360"
    }
  ],
  "schema_version": "1.7.3",
  "severity": [
    {
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "type": "CVSS_V3"
    }
  ],
  "summary": "Reachable assertion in Envoy"
}