{
  "id": "CVE-2021-28210",
  "details": "An unlimited recursion in DxeCore in EDK II.",
  "modified": "2024-09-03T03:47:13.910810Z",
  "published": "2021-06-11T16:15:12Z",
  "related": [
    "DLA-2645-1",
    "USN-4923-1"
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://bugzilla.tianocore.org/show_bug.cgi?id=1743"
    }
  ],
  "affected": [
    {
      "ranges": [
        {
          "type": "GIT",
          "repo": "https://github.com/tianocore/edk2",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "06dc822d045c2bb42e497487935485302486e151"
            }
          ]
        }
      ],
      "versions": [
        "edk2-stable201808",
        "edk2-stable201811",
        "edk2-stable201903",
        "edk2-stable201905",
        "edk2-stable201908",
        "edk2-stable201911",
        "edk2-stable202002",
        "edk2-stable202005"
      ],
      "database_specific": {
        "source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2021-28210.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H"
    }
  ]
}