{
  "affected": [
    {
      "database_specific": {
        "source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2025-59399.json"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0b84d7f9fb3c338d470770f220a7b7f21db78878"
            }
          ],
          "repo": "https://github.com/everest/libocpp",
          "type": "GIT"
        }
      ],
      "versions": [
        "v0.1.0",
        "v0.10.0",
        "v0.11.0",
        "v0.12.0",
        "v0.13.0",
        "v0.13.1",
        "v0.14.0",
        "v0.15.0",
        "v0.15.1",
        "v0.16.0",
        "v0.16.1",
        "v0.16.2",
        "v0.17.0",
        "v0.17.1",
        "v0.17.2",
        "v0.18.0",
        "v0.19.0",
        "v0.2.0",
        "v0.20.0",
        "v0.21.0",
        "v0.22.0",
        "v0.23.0",
        "v0.24.1",
        "v0.24.2",
        "v0.25.0",
        "v0.26.0",
        "v0.26.1",
        "v0.26.2",
        "v0.26.3",
        "v0.27.0",
        "v0.27.1",
        "v0.3.0",
        "v0.4.0",
        "v0.4.1",
        "v0.5.0",
        "v0.5.1",
        "v0.5.2",
        "v0.6.1",
        "v0.7.0",
        "v0.8.0",
        "v0.8.1",
        "v0.8.5",
        "v0.8.6",
        "v0.8.7",
        "v0.9.3",
        "v0.9.4",
        "v0.9.5",
        "v0.9.6",
        "v0.9.7",
        "v0.9.8"
      ]
    }
  ],
  "details": "libocpp before 0.28.0 allows a denial of service (EVerest crash) because a secondary exception is thrown during error message generation.",
  "id": "CVE-2025-59399",
  "modified": "2025-09-24T12:44:08.681134Z",
  "published": "2025-09-15T19:15:36Z",
  "references": [
    {
      "type": "FIX",
      "url": "https://github.com/EVerest/libocpp/commit/0b84d7f9fb3c338d470770f220a7b7f21db78878"
    },
    {
      "type": "WEB",
      "url": "https://github.com/EVerest/libocpp/compare/v0.27.1...v0.28.0"
    }
  ],
  "schema_version": "1.7.3"
}