{"schema_version":"1.7.3","id":"CVE-2018-12679","published":"2019-04-02T19:29:00Z","modified":"2025-10-21T04:29:30.120130Z","aliases":["GHSA-c6fm-rgw4-8q73","PYSEC-2019-166"],"details":"The Serialize.deserialize() method in CoAPthon3 1.0 and 1.0.1 mishandles certain exceptions, leading to a denial of service in applications that use this library (e.g., the standard CoAP server, CoAP client, example collect CoAP server and client) when they receive crafted CoAP messages.","affected":[{"ranges":[{"type":"GIT","repo":"https://github.com/tanganelli/coapthon3","events":[{"introduced":"0"},{"last_affected":"357b1afe4d09e6abd79a153111e46a9918b7172c"},{"last_affected":"fe716fff7aec2857761355500ad93b5185c6a427"}]}],"versions":["1.0","1.0.1","1.01"],"database_specific":{"source":"https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2018-12679.json"}}],"references":[{"type":"REPORT","url":"https://github.com/Tanganelli/CoAPthon3/issues/16"}],"severity":[{"type":"CVSS_V3","score":"CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"}]}