{
  "id": "CVE-2019-10742",
  "details": "Axios up to and including 0.18.0 allows attackers to cause a denial of service (application crash) by continuing to accepting content after maxContentLength is exceeded.",
  "aliases": [
    "GHSA-42xw-2xvc-qx8m"
  ],
  "modified": "2023-11-29T06:53:51.391052Z",
  "published": "2019-05-07T19:29:00Z",
  "withdrawn": "2024-05-15T05:33:48.742374Z",
  "references": [
    {
      "type": "WEB",
      "url": "https://app.snyk.io/vuln/SNYK-JS-AXIOS-174505"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/axios/axios/issues/1098"
    },
    {
      "type": "WEB",
      "url": "https://github.com/axios/axios/pull/1485"
    }
  ],
  "affected": [
    {
      "ranges": [
        {
          "type": "GIT",
          "repo": "https://github.com/axios/axios",
          "events": [
            {
              "introduced": "0"
            },
            {
              "last_affected": "d59c70fdfd35106130e9f783d0dbdcddd145b58f"
            }
          ]
        }
      ],
      "versions": [
        "v0.1.0",
        "v0.10.0",
        "v0.11.0",
        "v0.11.1",
        "v0.12.0",
        "v0.13.0",
        "v0.13.1",
        "v0.14.0",
        "v0.15.0",
        "v0.15.1",
        "v0.15.2",
        "v0.15.3",
        "v0.16.0",
        "v0.16.1",
        "v0.16.2",
        "v0.17.0",
        "v0.17.1",
        "v0.18.0",
        "v0.2.0",
        "v0.2.1",
        "v0.2.2",
        "v0.3.0",
        "v0.3.1",
        "v0.4.0",
        "v0.4.1",
        "v0.4.2",
        "v0.5.0",
        "v0.5.1",
        "v0.5.2",
        "v0.5.3",
        "v0.5.4",
        "v0.6.0",
        "v0.7.0",
        "v0.8.0",
        "v0.8.1",
        "v0.9.0",
        "v0.9.1"
      ],
      "database_specific": {
        "source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2019-10742.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ]
}