{
  "id": "CVE-2020-15214",
  "details": "In TensorFlow Lite before versions 2.2.1 and 2.3.1, models using segment sum can trigger a write out bounds / segmentation fault if the segment ids are not sorted. Code assumes that the segment ids are in increasing order, using the last element of the tensor holding them to determine the dimensionality of output tensor. This results in allocating insufficient memory for the output tensor and in a write outside the bounds of the output array. This usually results in a segmentation fault, but depending on runtime conditions it can provide for a write gadget to be used in future memory corruption-based exploits. The issue is patched in commit 204945b19e44b57906c9344c0d00120eeeae178a and is released in TensorFlow versions 2.2.1, or 2.3.1. A potential workaround would be to add a custom `Verifier` to the model loading code to ensure that the segment ids are sorted, although this only handles the case when the segment ids are stored statically in the model. A similar validation could be done if the segment ids are generated at runtime between inference steps. If the segment ids are generated as outputs of a tensor during inference steps, then there are no possible workaround and users are advised to upgrade to patched code.",
  "aliases": [
    "BIT-tensorflow-2020-15214",
    "GHSA-p2cq-cprg-frvm",
    "PYSEC-2020-137",
    "PYSEC-2020-294",
    "PYSEC-2020-329"
  ],
  "modified": "2024-05-13T22:24:53Z",
  "published": "2020-09-25T19:15:16Z",
  "references": [
    {
      "type": "EVIDENCE",
      "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-p2cq-cprg-frvm"
    },
    {
      "type": "FIX",
      "url": "https://github.com/tensorflow/tensorflow/commit/204945b19e44b57906c9344c0d00120eeeae178a"
    },
    {
      "type": "WEB",
      "url": "https://github.com/tensorflow/tensorflow/releases/tag/v2.3.1"
    }
  ],
  "affected": [
    {
      "ranges": [
        {
          "type": "GIT",
          "repo": "https://github.com/tensorflow/tensorflow",
          "events": [
            {
              "introduced": "2b96f3662bd776e277f86997659e61046b56c315"
            },
            {
              "introduced": "b36436b087bd8e8701ef51718179037cccdfc26e"
            },
            {
              "fixed": "204945b19e44b57906c9344c0d00120eeeae178a"
            }
          ]
        }
      ],
      "database_specific": {
        "source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2020-15214.json"
      },
      "versions": []
    }
  ],
  "schema_version": "1.6.0",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:L/I:L/A:H"
    }
  ]
}